# MULTIPLE REGRESSION

IMPORTING LIBRARIES

In [25]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import math
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
##### for one hot encoding i.e. converting text into numbers
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
##### for data spliting into train and test
from sklearn.model_selection import train_test_split


LOADING DATASET

In [22]:
dataset=pd.read_csv('/content/drive/My Drive/data/50_Startups.csv')
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

EXTRACTING RELAVENT COLUMNS VALUES ONLY (NO INDEX)

In [23]:
x=dataset[['R&D Spend','Administration','Marketing Spend','State']].values
y=dataset[['Profit']].values


CONVERTING STATE COLUMN INTO NUMBERS (ONE HOTT ENCODING)

In [24]:
st=ColumnTransformer([('State',OneHotEncoder(),[3])], remainder = 'passthrough')
x=st.fit_transform(x)
x

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

SPILITING OF DATA FOR TRAINING AND TESTING

In [31]:
# split 20 data into test while random_state=0 means not shuffling data 
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2,random_state=0)

TRAINING OF MODEL

In [32]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

PREDICTING MODEL AND PRINTING PREDICTED AND ACTUAL VALUES FOR COMPARISON

In [37]:
y_pred=model.predict(x_test)
print('y_pred:\n',y_pred)
print('y_test:\n',y_test)

y_pred:
 [[103015.20159795]
 [132582.27760816]
 [132447.73845175]
 [ 71976.09851258]
 [178537.48221057]
 [116161.24230167]
 [ 67851.69209676]
 [ 98791.73374687]
 [113969.43533014]
 [167921.06569552]]
y_test:
 [[103282.38]
 [144259.4 ]
 [146121.95]
 [ 77798.83]
 [191050.39]
 [105008.31]
 [ 81229.06]
 [ 97483.56]
 [110352.25]
 [166187.94]]


FINDING ACCURACY BY TAKING SUM AND THEN MEAN OF ALL PREDICTED VALUES AND THEN DIVIDING IT SUM AND MEAN OF ALL ACTUAL TEST VALES

In [40]:
print ('the so-called accuracy is:\t', y_pred.sum().mean()/y_test.sum().mean())

the so-called accuracy is:	 0.9676799636027315
